-- =========================
-- TABLA: categorias
-- =========================
create table if not exists public.categorias (
  idcategoria bigint generated by default as identity primary key,
  id text generated always as (idcategoria::text) stored,
  nombre text not null unique,
  descripcion text
);

-- =========================
-- TABLA: usuario
-- =========================
create table if not exists public.usuario (
  idusuario bigint generated by default as identity primary key,
  nombre text not null,
  email text not null unique,
  contrasena text not null,
  rol text not null default 'admin',
  constraint usuario_rol_check
    check (rol in ('admin', 'vendedor', 'repartidor', 'cliente'))
);

-- =========================
-- TABLA: cliente
-- =========================
create table if not exists public.cliente (
  idcliente bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  direccion text,
  email text not null unique,
  created_at timestamptz not null default now()
);

-- =========================
-- TABLA: producto
-- Nota: "imgUrl" va entre comillas porque el backend la consulta con ese nombre exacto.
-- =========================
create table if not exists public.producto (
  idproducto bigint generated by default as identity primary key,
  id text generated always as (idproducto::text) stored,
  nombre text not null,
  descripcion text not null default '',
  precio numeric(10,2) not null check (precio >= 0),
  "imgUrl" text,
  categoria_id bigint references public.categorias(idcategoria)
    on update cascade
    on delete set null,
  stock integer not null default 0 check (stock >= 0),
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

-- =========================
-- TABLA: pedido
-- =========================
create table if not exists public.pedido (
  idpedido bigint generated by default as identity primary key,
  fecha date not null default current_date,
  estado text not null default 'pendiente',
  nombrecliente text not null,
  direccion text,
  notas text,
  total numeric(10,2) not null default 0 check (total >= 0),
  idcliente bigint not null references public.cliente(idcliente)
    on update cascade
    on delete restrict,
  idusuario bigint not null references public.usuario(idusuario)
    on update cascade
    on delete restrict,
  created_at timestamptz not null default now(),
  constraint pedido_estado_check
    check (estado in ('pendiente', 'en preparación', 'en reparto', 'entregado', 'cancelado'))
);

-- =========================
-- TABLA: detallepedido
-- =========================
create table if not exists public.detallepedido (
  iddetalle bigint generated by default as identity primary key,
  idpedido bigint not null references public.pedido(idpedido)
    on update cascade
    on delete cascade,
  idproducto bigint not null references public.producto(idproducto)
    on update cascade
    on delete restrict,
  cantidad integer not null check (cantidad > 0),
  subtotal numeric(10,2) not null check (subtotal >= 0)
);

-- =========================
-- ÍNDICES ÚTILES
-- =========================
create index if not exists idx_producto_categoria_id
  on public.producto(categoria_id);

create index if not exists idx_pedido_fecha
  on public.pedido(fecha);

create index if not exists idx_pedido_estado
  on public.pedido(estado);

create index if not exists idx_detallepedido_idpedido
  on public.detallepedido(idpedido);

create index if not exists idx_detallepedido_idproducto
  on public.detallepedido(idproducto);